# REDES NEURAIS ARTIFICIAIS

[Aula 3 de Deep Learning](http://bit.ly/dn-unb03) da Engenharia de Software da UnB

In [1]:
#! pip install -r requirements.txt
# Installing Theano
! pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Install other packages
! pip install --upgrade pip pandas matplotlib sklearn tensorflow keras==2.2.5

  Cloning git://github.com/Theano/Theano.git to /tmp/pip-req-build-i22b1xpl
  Created wheel for Theano: filename=Theano-1.0.5+1.geb6a4125c-py3-none-any.whl size=2668281 sha256=45a5047553327793dd9c4f87f24fd414f752288d283432457875ca385405f16f
  Stored in directory: /tmp/pip-ephem-wheel-cache-_bctt2jv/wheels/31/0b/3d/ec0a7d000aed975d9ad70a301a3bd2c5fcdab43b1eba72eb59
Successfully built Theano
  Attempting uninstall: Theano
    Found existing installation: Theano 1.0.5+1.geb6a4125c
    Uninstalling Theano-1.0.5+1.geb6a4125c:
      Successfully uninstalled Theano-1.0.5+1.geb6a4125c
Requirement already up-to-date: pip in /home/isaque/Envs/buidingann/lib/python3.6/site-packages (20.2.3)
Requirement already up-to-date: pandas in /home/isaque/Envs/buidingann/lib/python3.6/site-packages (1.1.2)
Requirement already up-to-date: matplotlib in /home/isaque/Envs/buidingann/lib/python3.6/site-packages (3.3.2)
Requirement already up-to-date: sklearn in /home/isaque/Envs/buidingann/lib/python3.6/site-pa

# Parte 1 - Preprocessamento dos Dados

### Importar as libs

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

### Importar o dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
print("X >>\n")
print(X)
print("y >>\n",y)


X >>

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
y >>
 [1 0 1 ... 1 1 0]


### Transformando os dados categóricos


In [4]:
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])

transformer = ColumnTransformer(
    transformers=[
        ("OneHot",
         OneHotEncoder(),
         [1]
         )
    ],
    remainder = 'passthrough'
)
X = transformer.fit_transform(X)

X = X[:, 1:]
print("X >>\n",X)

X >>
 [[0.0 0.0 619 ... 1 1 101348.88]
 [0.0 1.0 608 ... 0 1 112542.58]
 [0.0 0.0 502 ... 1 0 113931.57]
 ...
 [0.0 0.0 709 ... 0 1 42085.58]
 [1.0 0.0 772 ... 1 0 92888.52]
 [0.0 0.0 792 ... 1 0 38190.78]]


# Dividindo o dataset em conjunto de treinamento e conjunto de teste

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

---
# Parte 2 -Vamos construir uma ANN!

## Importando o Keras


In [11]:
#import keras
#from keras.models import Sequential
#from keras.layers import Dense

from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras import Sequential

In [36]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'softsign', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'softplus'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Ajustando a ANN ao conjunto de treinamento

In [37]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 1s 646us/step - loss: 0.4774 - accuracy: 0.7960
Epoch 2/100
800/800 [==============================] - 0s 610us/step - loss: 0.4306 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 1s 647us/step - loss: 0.4288 - accuracy: 0.7960
Epoch 4/100
800/800 [==============================] - 1s 653us/step - loss: 0.4284 - accuracy: 0.7960
Epoch 5/100
800/800 [==============================] - 1s 660us/step - loss: 0.4278 - accuracy: 0.7958
Epoch 6/100
800/800 [==============================] - 0s 602us/step - loss: 0.4268 - accuracy: 0.7952
Epoch 7/100
800/800 [==============================] - 1s 650us/step - loss: 0.4254 - accuracy: 0.7949
Epoch 8/100
800/800 [==============================] - 1s 674us/step - loss: 0.4232 - accuracy: 0.7986
Epoch 9/100
800/800 [==============================] - 1s 645us/step - loss: 0.4190 - accuracy: 0.8052
Epoch 10/100
800/800 [==============================] - 0s 604us/step - l

800/800 [==============================] - 1s 640us/step - loss: 0.3363 - accuracy: 0.8645
Epoch 80/100
800/800 [==============================] - 0s 618us/step - loss: 0.3357 - accuracy: 0.8636
Epoch 81/100
800/800 [==============================] - 1s 685us/step - loss: 0.3364 - accuracy: 0.8640
Epoch 82/100
800/800 [==============================] - 1s 637us/step - loss: 0.3361 - accuracy: 0.8633
Epoch 83/100
800/800 [==============================] - 0s 620us/step - loss: 0.3357 - accuracy: 0.8627
Epoch 84/100
800/800 [==============================] - 1s 663us/step - loss: 0.3363 - accuracy: 0.8636
Epoch 85/100
800/800 [==============================] - 1s 645us/step - loss: 0.3357 - accuracy: 0.8629
Epoch 86/100
800/800 [==============================] - 1s 631us/step - loss: 0.3353 - accuracy: 0.8654
Epoch 87/100
800/800 [==============================] - 1s 653us/step - loss: 0.3356 - accuracy: 0.8649
Epoch 88/100
800/800 [==============================] - 0s 618us/step - loss:

# Parte 3 - Fazendo predições e avaliando o modelo

## Prevendo os resultados com o conjunto de testes

In [38]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Criando uma Confusion Matrix

In [39]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1499   96]
 [ 185  220]]


# Initiate activation function experimentation

# Initialising the 2nd ANN

In [44]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'sigmoid', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'selu'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 1s 639us/step - loss: 0.4990 - accuracy: 0.7955
Epoch 2/100
800/800 [==============================] - 0s 622us/step - loss: 0.4414 - accuracy: 0.7970
Epoch 3/100
800/800 [==============================] - 0s 608us/step - loss: 0.4302 - accuracy: 0.8043
Epoch 4/100
800/800 [==============================] - 0s 617us/step - loss: 0.4283 - accuracy: 0.8039
Epoch 5/100
800/800 [==============================] - 1s 649us/step - loss: 0.4280 - accuracy: 0.8043
Epoch 6/100
800/800 [==============================] - 0s 621us/step - loss: 0.4276 - accuracy: 0.8046
Epoch 7/100
800/800 [==============================] - 1s 650us/step - loss: 0.4276 - accuracy: 0.8061
Epoch 8/100
800/800 [==============================] - 1s 660us/step - loss: 0.4271 - accuracy: 0.8055
Epoch 9/100
800/800 [==============================] - 1s 646us/step - loss: 0.4266 - accuracy: 0.8062
Epoch 10/100
800/800 [==============================] - 1s 628us/step - l

800/800 [==============================] - 1s 635us/step - loss: 0.3841 - accuracy: 0.8391
Epoch 80/100
800/800 [==============================] - 1s 664us/step - loss: 0.3829 - accuracy: 0.8411
Epoch 81/100
800/800 [==============================] - 1s 681us/step - loss: 0.3817 - accuracy: 0.8421
Epoch 82/100
800/800 [==============================] - 1s 656us/step - loss: 0.3798 - accuracy: 0.8406
Epoch 83/100
800/800 [==============================] - 1s 669us/step - loss: 0.3773 - accuracy: 0.8424
Epoch 84/100
800/800 [==============================] - 0s 610us/step - loss: 0.3741 - accuracy: 0.8436
Epoch 85/100
800/800 [==============================] - 1s 653us/step - loss: 0.3705 - accuracy: 0.8434
Epoch 86/100
800/800 [==============================] - 0s 607us/step - loss: 0.3654 - accuracy: 0.8474
Epoch 87/100
800/800 [==============================] - 0s 622us/step - loss: 0.3602 - accuracy: 0.8464
Epoch 88/100
800/800 [==============================] - 0s 613us/step - loss:

In [45]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [46]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1502   93]
 [ 195  210]]


# Initialising the 3rd ANN

In [47]:
del classifier

classifier = Sequential()

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'softmax', input_dim = 11))

classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 1s 688us/step - loss: 0.5388 - accuracy: 0.7949
Epoch 2/100
800/800 [==============================] - 1s 681us/step - loss: 0.4410 - accuracy: 0.7961
Epoch 3/100
800/800 [==============================] - 1s 678us/step - loss: 0.4215 - accuracy: 0.8090
Epoch 4/100
800/800 [==============================] - 1s 672us/step - loss: 0.4098 - accuracy: 0.8185
Epoch 5/100
800/800 [==============================] - 1s 656us/step - loss: 0.3931 - accuracy: 0.8322
Epoch 6/100
800/800 [==============================] - 1s 685us/step - loss: 0.3765 - accuracy: 0.8460
Epoch 7/100
800/800 [==============================] - 1s 642us/step - loss: 0.3638 - accuracy: 0.8547
Epoch 8/100
800/800 [==============================] - 1s 627us/step - loss: 0.3552 - accuracy: 0.8586
Epoch 9/100
800/800 [==============================] - 1s 644us/step - loss: 0.3505 - accuracy: 0.8625
Epoch 10/100
800/800 [==============================] - 1s 662us/step - l

800/800 [==============================] - 1s 646us/step - loss: 0.3349 - accuracy: 0.8629
Epoch 80/100
800/800 [==============================] - 1s 658us/step - loss: 0.3351 - accuracy: 0.8640
Epoch 81/100
800/800 [==============================] - 1s 686us/step - loss: 0.3349 - accuracy: 0.8630
Epoch 82/100
800/800 [==============================] - 1s 685us/step - loss: 0.3348 - accuracy: 0.8629
Epoch 83/100
800/800 [==============================] - 1s 677us/step - loss: 0.3349 - accuracy: 0.8634
Epoch 84/100
800/800 [==============================] - 1s 656us/step - loss: 0.3350 - accuracy: 0.8636
Epoch 85/100
800/800 [==============================] - 1s 653us/step - loss: 0.3350 - accuracy: 0.8633
Epoch 86/100
800/800 [==============================] - 1s 658us/step - loss: 0.3353 - accuracy: 0.8629
Epoch 87/100
800/800 [==============================] - 1s 636us/step - loss: 0.3348 - accuracy: 0.8629
Epoch 88/100
800/800 [==============================] - 1s 674us/step - loss:

In [19]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix

In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1547   48]
 [ 265  140]]


---
# Parte 4 - Evaluating, Improving and Tuning the ANN

## Evaluating the ANN

In [48]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()
print("accuracies:%s\nmean:%s\nvariance:%s".format(accuracies, mean, variance))

accuracies:%s
mean:%s
variance:%s


# Improving the ANN
# Dropout Regularization to reduce overfitting if needed

In [ ]:
from keras.layers import Dropout

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier, batch_size = 10, epochs = 10)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)
mean = accuracies.mean()
variance = accuracies.std()

# Tuning the ANN

In [ ]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dropout(rate = 0.1))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)

In [ ]:
parameters = {'batch_size': [10, 24, 32],
              'epochs': [50, 100, 200],
              'optimizer': ['adam', 'rmsprop']}

grid_search = GridSearchCV(estimator = classifier,
                           scoring = 'accuracy',
                           param_grid = parameters,
                           cv = 10)

grid_search = grid_search.fit(X_train, y_train)

best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

# FIM

> Professor Diego Dorgam  
> [@diegodorgam](https://twitter.com/diegodorgam)